// constants/learningExperiences.js

export const learningExperiences = [
  {
    title: "IT Business Analyst",
    company_name: "PT YAIJ Solusi Internasional",
    icon: "", 
    iconBg: "#FFF",
    date: "December 2025 - Present",
    contents: [
      "Led end-to-end development of YAIJ: Cek Karir, generating 200+ qualified leads and attracting 3,000+ visitors during launch.",
      "Architected an enterprise management platform spanning 8+ operational modules, 9 user roles, and 4 external integrations, streamlining workflows across multiple business functions.",
      "Partnered with the Project Manager to translate business requirements into scalable technical solutions, reducing data processing and content production time by ~60% through automation, centralized data architecture, and workflow optimization.",
      "Established a containerized CI/CD infrastructure with GitHub Actions, Docker, and VPS deployment, supported by 90+ automated tests to ensure application quality and deployment consistency.",
    ],
  },
  {
    title: "Frontend Developer (Intern)",
    company_name: "Human Centric Research Center Telkom University",
    icon: "", 
    iconBg: "#FFF",
    date: "September 2025 - January 2026",
    contents: [
      "Developed dynamic conferencing applications with multi-role users, helping to simplify content creation with a 40% improvement.",
      "Contributed to a research-based application registered as Intellectual Property (HKI), ensuring originality and legal protection of the developed system.",
    ],
  },
  {
    title: "Assistant Lecturer | MySQL (DDL, DML)",
    company_name: "Universitas Pendidikan Indonesia",
    icon: "", 
    iconBg: "#FFF",
    date: "September 2025 - January 2026",
    contents: [
      "Assisted lecturers in teaching Database Modeling, Basic Programming, and Software Design & Specification courses for 90+ students.",
    ],
  },
  {
    title: "Founder (Fullstack Developer, IT Business Analyst)",
    company_name: "GABOOTHZ: Gallery Photobooth",
    icon: "", 
    iconBg: "#FFF",
    date: "February 2025 - Present",
    contents: [
      "Collaborated with 5+ stakeholders to deliver a seamless digital photobooth experience.",
      "Collaborated with 3 people to build Gaboothz and Generated more than IDR 10 million in revenue through commercial photobooth services.",
      "Selected as a finalist in UPI Edupreneur Academy's Business Entrepreneurship Program.",
    ],
  },
  {
    title: "Fullstack Web Development",
    company_name: "Self-Taught / Online Resources",
    icon: "/assets/logos/javascript.svg",
    iconBg: "#000000",
    date: "September 2023 - Present",
    contents: [
      "Learned the fundamentals of web development using HTML, CSS, and JavaScript.",
      "Developed responsive and interactive websites from scratch.",
      "Understood basic concepts of DOM manipulation and event handling.",
      "Applied best practices for clean and organized code structure.",
      "Fetching data and interacting with APIs.",
    ],
  },
  {
    title: "Python Development",
    company_name: "College Material, Self-Taught / Online Resources",
    icon: "/assets/logos/python.svg",
    iconBg: "#000000",
    date: "September 2023 - Present",
    contents: [
      "Delved into Python for data analysis using Pandas.",
      "Learned the basics of Artificial Intelligence (AI) and Machine Learning (ML).",
      "Utilized development environments like Conda and Jupyter Notebook for data experimentation.",
    ],
  },
  {
    title: "C++ Data Structures & Algorithms",
    company_name: "College Material",
    icon: "/assets/logos/cplusplus.svg",
    iconBg: "#000000",
    date: "January 2024 - June 2024",
    contents: [
      "Studied the implementation and usage of various Data Structures: Stack, Queue, Linked List, Tree (Binary Tree, BST), Hash Table, Heap.",
      "Explored Algorithms: Depth-First Search (DFS), Breadth-First Search (BFS), Sorting Algorithms (Merge Sort, Quick Sort), Searching Algorithms.",
      "Understood Pointer concepts and Memory Management in C++.",
      "Applied algorithms to solve complex computational problems.",
    ],
  },
  {
    title: "Java OOP Programming",
    company_name: "College Material",
    icon: "/assets/logos/java.svg",
    iconBg: "#000000",
    date: "February 2025 - Present",
    contents: [
      "Learned Object-Oriented Programming (OOP) concepts in depth: Encapsulation, Inheritance, Polymorphism, Abstraction.",
      "Delved into Functional Programming concepts in Java.",
      "Understood the use of Collections Framework and exception handling.",
    ],
  },
  {
    title: "MySQL Database Management",
    company_name: "College Material",
    icon: "/assets/logos/logo-mysql.png",
    iconBg: "#000000",
    date: "September 2024 - Present",
    contents: [
      "Mastered SQL fundamentals for data manipulation and querying.",
      "Learned database, table, and index creation and management.",
      "Understood Views, Triggers, Functions, and Stored Procedures for database efficiency.",
      "Analyzed and optimized database query performance.",
    ],
  },
  {
    title: "React.js Web Development",
    company_name: "Self-Taught / Online Resources",
    icon: "/assets/logos/react.svg",
    iconBg: "#000000",
    date: "February 2024 - Present",
    contents: [
      "Learned React.js fundamentals: Components, Props, State, and Hooks (useState, useEffect, useRef).",
      "Built interactive and dynamic Single Page Applications (SPA).",
      "Understood Virtual DOM and Reconciliation concepts.",
      "Utilized React Router for client-side routing.",
      "Applied best practices for code organization and maintainability.",
    ],
  },
];
