// constants/projects.js
// Fill in the category with Website, UI/UX, Mobile, Desktop, Terminal 

// Keyword: List Projects
export const listProjects = [
  {
    id: 0,
    slug: 'factory-agent-ai',
    title: 'Factory Agent: AI Agent Mission Control',
    description: 'Factory Agent is a sophisticated AI Agent ecosystem built on OpenClaw, featuring a comprehensive Mission Control Dashboard. This project simulates a corporate hierarchy where AI Agents take on specific divisional roles—acting as representatives across various departments to optimize workflows and project management.',
    image: '/assets/projects/Factory-Agent.png',
    images: [
      '/assets/projects/Factory-Agent.png',
      '/assets/projects/Factory-Dashboard.png',
      '/assets/projects/Factory-Modal.png'
    ],
    tags: ['React', 'OpenClaw', 'AI Agent', 'Dashboard'],
    githubUrl: 'https://github.com/fatraelkarizm/factory-agent',
    category: 'Website',
  },
  {
    id: 1,
    slug: 'komikan-modern-comic',
    title: 'Komikan: Modern Comic Website (Under Development)',
    description: 'This is a modern, user-focused web design for a digital comic reading platform. The interface emphasizes readability, engagement, and discoverability through a sleek dark mode layout and anime-style visuals.',
    image: '/assets/projects/Design Web Comic.png',
    tags: ['React', 'Laravel', 'Figma'],
    category: 'Website',
  },
  {
    id: 2,
    slug: 'financial-projection-dashboard',
    title: 'Financial Projection Dashboard',
    description: 'A modern web-based financial dashboard designed to track income, expenses, and growth in real-time. Fully integrated with Google Spreadsheet as the backend, it allows seamless data management without the need for a separate server. ',
    image: '/assets/projects/FinancialProjection.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'CSV'],
    category: 'Website',
  },
  {
    id: 3,
    slug: 'data-dash',
    title: 'Data Dash',
    description: 'DataDash is a lightweight web app built for quickly visualizing CSV data without the need for backend processing. Users can drag and drop CSV files (up to 100MB) to instantly explore and analyze data in a clean, interactive dashboard.',
    image: '/assets/projects/DataDash.png',
    tags: ['HTML', 'TailwindCSS', 'JavaScript', 'Spreadsheet'],
    category: 'Website',
  },
  {
    id: 4,
    slug: 'gaboothz-gallery-photoboothz',
    title: 'Gaboothz: Gallery Photoboothz',
    description: 'Gaboothz, or Gallery Photoboothz, is an online platform or application designed for capturing and displaying photobooth pictures. It allows users to initiate a photo session ("Start Photo") and then view a gallery of the resulting photo strips, which likely include various layouts (templates) and styles. Essentially, it serves as a digital hub for photobooth experiences, providing both the means to take photos and a place to showcase them.',
    image: '/assets/projects/Gaboothz.png',
    tags: ['React','TypeScript','Laravel', 'MySQL'],
    demoUrl: 'https://gaboothz.web.id',
    category: 'Website',
  },
  {
    id: 5,
    slug: 'stylo-a-website',
    title: 'Stylo: A Website for Fashion Suggestion',
    description: 'Stylo is an innovative web platform harnessing the power of Artificial Intelligence and Web3 technology to redefine personal style. It empowers users to generate their own unique digital outfits, offering a glimpse into the next-gen fashion era. Beyond creation, Stylo also curates and showcases top fashion suggestions, potentially allowing community engagement through voting on the best designs.',
    image: '/assets/projects/StyloWeb3.png',
    tags: ['React','Figma'],
    githubUrl: 'https://icp.ninja/s/Gn1rw',
    category: 'UI/UX',
  },
  {
    id: 6,
    slug: 'ayo-academy-final',
    title: 'AYO Academy: Final Business and Entrepreneurship Project',
    description: 'The MentalHealth app is a digital platform designed to provide accessible support and resources for mental well-being, offering features such as consultations, an AI chat room, and dedicated healing resources to help users manage and improve their mental health.',
    image: '/assets/projects/AYO_BE.png',
    tags: ['Figma'],
    demoUrl: 'https://www.figma.com/proto/nadSOn0QzCmTKsRO5wznfV/Mental-Health?node-id=8-230&t=0en5b8yVQ4UeHRRm-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=8%3A230',
    category: 'UI/UX',
  },
  {
    id: 7,
    slug: 'lost-found-a',
    title: 'Lost & Found: A Lost Item Finder App',
    description: 'Lost & Found is a web application designed to help users locate lost items by allowing them to post details about their lost belongings and search for items that others have found. It aims to create a community-driven platform for recovering lost items efficiently.',
    image: '/assets/projects/LostFound.png',
    tags: ['React', 'TypeScript', 'Laravel', 'MySQL'],
    githubUrl: 'https://github.com/fatraelkarizm/Lost-Found',
    category: 'Website',
  },
  {
    id: 8,
    slug: 'marketeers-mobile-optimize',
    title: 'Marketeers: Mobile Optimize for MyPertamina',
    description: 'A project focused on optimizing the MyPertamina mobile application, enhancing user experience and accessibility through a user-centered design approach.',
    image: '/assets/projects/Marketeer_Mobile.png',
    tags: ['Figma'],
    category: 'UI/UX',
  },
  {
    id: 9,
    slug: 'marketeers-website-optimize',
    title: 'Marketeers: Website Optimize for Pertamax Green 95',
    description: 'A project focused on optimizing the website for Pertamax Green 95, enhancing user experience and accessibility.',
    image: '/assets/projects/Marketeers.png',
    tags: ['Figma'],
    category: 'UI/UX',
  },
];

